/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_seetaface_v6_FaceLandMarker */

#ifndef _Included_com_seetaface_v6_FaceLandMarker
#define _Included_com_seetaface_v6_FaceLandMarker
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_seetaface_v6_FaceLandMarker
 * Method:    nativeCreateEngine
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_seetaface_v6_FaceLandMarker_nativeCreateEngine
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_seetaface_v6_FaceLandMarker
 * Method:    nativeDestroyEngine
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_seetaface_v6_FaceLandMarker_nativeDestroyEngine
  (JNIEnv *, jobject);

/*
 * Class:     com_seetaface_v6_FaceLandMarker
 * Method:    nativeGetPointsLength
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_seetaface_v6_FaceLandMarker_nativeGetPointsLength
  (JNIEnv *, jobject);

/*
 * Class:     com_seetaface_v6_FaceLandMarker
 * Method:    nativeGetFacePoints
 * Signature: (Lcom/seetaface/v6/SeetaImageData;Lcom/seetaface/v6/SeetaRect;)[Lcom/seetaface/v6/SeetaPointF;
 */
JNIEXPORT jobjectArray JNICALL Java_com_seetaface_v6_FaceLandMarker_nativeGetFacePoints__Lcom_seetaface_v6_SeetaImageData_2Lcom_seetaface_v6_SeetaRect_2
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     com_seetaface_v6_FaceLandMarker
 * Method:    nativeGetFacePoints
 * Signature: (Lcom/seetaface/v6/SeetaImageData;Lcom/seetaface/v6/SeetaRect;[Lcom/seetaface/v6/SeetaPointF;)V
 */
JNIEXPORT void JNICALL Java_com_seetaface_v6_FaceLandMarker_nativeGetFacePoints__Lcom_seetaface_v6_SeetaImageData_2Lcom_seetaface_v6_SeetaRect_2_3Lcom_seetaface_v6_SeetaPointF_2
  (JNIEnv *, jobject, jobject, jobject, jobjectArray);

/*
 * Class:     com_seetaface_v6_FaceLandMarker
 * Method:    nativeGetFacePointsWithMask
 * Signature: (Lcom/seetaface/v6/SeetaImageData;Lcom/seetaface/v6/SeetaRect;)[Lcom/seetaface/v6/SeetaPointsWithMask;
 */
JNIEXPORT jobjectArray JNICALL Java_com_seetaface_v6_FaceLandMarker_nativeGetFacePointsWithMask__Lcom_seetaface_v6_SeetaImageData_2Lcom_seetaface_v6_SeetaRect_2
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     com_seetaface_v6_FaceLandMarker
 * Method:    nativeGetFacePointsWithMask
 * Signature: (Lcom/seetaface/v6/SeetaImageData;Lcom/seetaface/v6/SeetaRect;[Lcom/seetaface/v6/SeetaPointsWithMask;)V
 */
JNIEXPORT void JNICALL Java_com_seetaface_v6_FaceLandMarker_nativeGetFacePointsWithMask__Lcom_seetaface_v6_SeetaImageData_2Lcom_seetaface_v6_SeetaRect_2_3Lcom_seetaface_v6_SeetaPointsWithMask_2
  (JNIEnv *, jobject, jobject, jobject, jobjectArray);

#ifdef __cplusplus
}
#endif
#endif
