/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_seetaface_v6_GenderPredictor */

#ifndef _Included_com_seetaface_v6_GenderPredictor
#define _Included_com_seetaface_v6_GenderPredictor
#ifdef __cplusplus
extern "C" {
#endif
#undef com_seetaface_v6_GenderPredictor_GENDER_MALE
#define com_seetaface_v6_GenderPredictor_GENDER_MALE 0L
#undef com_seetaface_v6_GenderPredictor_GENDER_FEMALE
#define com_seetaface_v6_GenderPredictor_GENDER_FEMALE 1L
#undef com_seetaface_v6_GenderPredictor_PROPERTY_NUMBER_THREADS
#define com_seetaface_v6_GenderPredictor_PROPERTY_NUMBER_THREADS 4L
#undef com_seetaface_v6_GenderPredictor_PROPERTY_ARM_CPU_MODE
#define com_seetaface_v6_GenderPredictor_PROPERTY_ARM_CPU_MODE 5L
/*
 * Class:     com_seetaface_v6_GenderPredictor
 * Method:    nativeCreateEngine
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_seetaface_v6_GenderPredictor_nativeCreateEngine
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_seetaface_v6_GenderPredictor
 * Method:    nativeDestroyEngine
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_seetaface_v6_GenderPredictor_nativeDestroyEngine
  (JNIEnv *, jobject);

/*
 * Class:     com_seetaface_v6_GenderPredictor
 * Method:    nativeGetCropFaceWidth
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_seetaface_v6_GenderPredictor_nativeGetCropFaceWidth
  (JNIEnv *, jobject);

/*
 * Class:     com_seetaface_v6_GenderPredictor
 * Method:    nativeGetCropFaceHeight
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_seetaface_v6_GenderPredictor_nativeGetCropFaceHeight
  (JNIEnv *, jobject);

/*
 * Class:     com_seetaface_v6_GenderPredictor
 * Method:    nativeGetCropFaceChannels
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_seetaface_v6_GenderPredictor_nativeGetCropFaceChannels
  (JNIEnv *, jobject);

/*
 * Class:     com_seetaface_v6_GenderPredictor
 * Method:    nativeCropFace
 * Signature: (Lcom/seetaface/v6/SeetaImageData;[Lcom/seetaface/v6/SeetaPointF;Lcom/seetaface/v6/SeetaImageData;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_seetaface_v6_GenderPredictor_nativeCropFace
  (JNIEnv *, jobject, jobject, jobjectArray, jobject);

/*
 * Class:     com_seetaface_v6_GenderPredictor
 * Method:    nativePredictGender
 * Signature: (Lcom/seetaface/v6/SeetaImageData;)I
 */
JNIEXPORT jint JNICALL Java_com_seetaface_v6_GenderPredictor_nativePredictGender
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_seetaface_v6_GenderPredictor
 * Method:    nativePredictGenderWithCrop
 * Signature: (Lcom/seetaface/v6/SeetaImageData;[Lcom/seetaface/v6/SeetaPointF;)I
 */
JNIEXPORT jint JNICALL Java_com_seetaface_v6_GenderPredictor_nativePredictGenderWithCrop
  (JNIEnv *, jobject, jobject, jobjectArray);

/*
 * Class:     com_seetaface_v6_GenderPredictor
 * Method:    nativeSetProperty
 * Signature: (ID)V
 */
JNIEXPORT void JNICALL Java_com_seetaface_v6_GenderPredictor_nativeSetProperty
  (JNIEnv *, jobject, jint, jdouble);

/*
 * Class:     com_seetaface_v6_GenderPredictor
 * Method:    nativeGetProperty
 * Signature: (I)D
 */
JNIEXPORT jdouble JNICALL Java_com_seetaface_v6_GenderPredictor_nativeGetProperty
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
