/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_seetaface_v6_FaceTracker */

#ifndef _Included_com_seetaface_v6_FaceTracker
#define _Included_com_seetaface_v6_FaceTracker
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_seetaface_v6_FaceTracker
 * Method:    nativeCreateEngine
 * Signature: (Ljava/lang/String;II)I
 */
JNIEXPORT jint JNICALL Java_com_seetaface_v6_FaceTracker_nativeCreateEngine
  (JNIEnv *, jobject, jstring, jint, jint);

/*
 * Class:     com_seetaface_v6_FaceTracker
 * Method:    nativeDestroyEngine
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_seetaface_v6_FaceTracker_nativeDestroyEngine
  (JNIEnv *, jobject);

/*
 * Class:     com_seetaface_v6_FaceTracker
 * Method:    nativeSetSingleCalculationThreads
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_seetaface_v6_FaceTracker_nativeSetSingleCalculationThreads
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_seetaface_v6_FaceTracker
 * Method:    nativeSetMinFaceSize
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_seetaface_v6_FaceTracker_nativeSetMinFaceSize
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_seetaface_v6_FaceTracker
 * Method:    nativeGetMinFaceSize
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_seetaface_v6_FaceTracker_nativeGetMinFaceSize
  (JNIEnv *, jobject);

/*
 * Class:     com_seetaface_v6_FaceTracker
 * Method:    nativeSetThreshold
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_com_seetaface_v6_FaceTracker_nativeSetThreshold
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     com_seetaface_v6_FaceTracker
 * Method:    nativeGetScoreThreshold
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_com_seetaface_v6_FaceTracker_nativeGetScoreThreshold
  (JNIEnv *, jobject);

/*
 * Class:     com_seetaface_v6_FaceTracker
 * Method:    nativeSetVideoStable
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_com_seetaface_v6_FaceTracker_nativeSetVideoStable
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     com_seetaface_v6_FaceTracker
 * Method:    nativeGetVideoStable
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_seetaface_v6_FaceTracker_nativeGetVideoStable
  (JNIEnv *, jobject);

/*
 * Class:     com_seetaface_v6_FaceTracker
 * Method:    nativeTrack
 * Signature: (Lcom/seetaface/v6/SeetaImageData;)[Lcom/seetaface/v6/SeetaTrackingFaceInfo;
 */
JNIEXPORT jobjectArray JNICALL Java_com_seetaface_v6_FaceTracker_nativeTrack__Lcom_seetaface_v6_SeetaImageData_2
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_seetaface_v6_FaceTracker
 * Method:    nativeTrack
 * Signature: (Lcom/seetaface/v6/SeetaImageData;I)[Lcom/seetaface/v6/SeetaTrackingFaceInfo;
 */
JNIEXPORT jobjectArray JNICALL Java_com_seetaface_v6_FaceTracker_nativeTrack__Lcom_seetaface_v6_SeetaImageData_2I
  (JNIEnv *, jobject, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
