/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_seetaface_v6_AgePredictor */

#ifndef _Included_com_seetaface_v6_AgePredictor
#define _Included_com_seetaface_v6_AgePredictor
#ifdef __cplusplus
extern "C" {
#endif
#undef com_seetaface_v6_AgePredictor_PROPERTY_NUMBER_THREADS
#define com_seetaface_v6_AgePredictor_PROPERTY_NUMBER_THREADS 4L
#undef com_seetaface_v6_AgePredictor_PROPERTY_ARM_CPU_MODE
#define com_seetaface_v6_AgePredictor_PROPERTY_ARM_CPU_MODE 5L
/*
 * Class:     com_seetaface_v6_AgePredictor
 * Method:    nativeCreateEngine
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_seetaface_v6_AgePredictor_nativeCreateEngine
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_seetaface_v6_AgePredictor
 * Method:    nativeDestroyEngine
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_seetaface_v6_AgePredictor_nativeDestroyEngine
  (JNIEnv *, jobject);

/*
 * Class:     com_seetaface_v6_AgePredictor
 * Method:    nativeGetCropFaceWidth
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_seetaface_v6_AgePredictor_nativeGetCropFaceWidth
  (JNIEnv *, jobject);

/*
 * Class:     com_seetaface_v6_AgePredictor
 * Method:    nativeGetCropFaceHeight
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_seetaface_v6_AgePredictor_nativeGetCropFaceHeight
  (JNIEnv *, jobject);

/*
 * Class:     com_seetaface_v6_AgePredictor
 * Method:    nativeGetCropFaceChannels
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_seetaface_v6_AgePredictor_nativeGetCropFaceChannels
  (JNIEnv *, jobject);

/*
 * Class:     com_seetaface_v6_AgePredictor
 * Method:    nativeCropFace
 * Signature: (Lcom/seetaface/v6/SeetaImageData;[Lcom/seetaface/v6/SeetaPointF;Lcom/seetaface/v6/SeetaImageData;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_seetaface_v6_AgePredictor_nativeCropFace
  (JNIEnv *, jobject, jobject, jobjectArray, jobject);

/*
 * Class:     com_seetaface_v6_AgePredictor
 * Method:    nativePredictAge
 * Signature: (Lcom/seetaface/v6/SeetaImageData;)I
 */
JNIEXPORT jint JNICALL Java_com_seetaface_v6_AgePredictor_nativePredictAge
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_seetaface_v6_AgePredictor
 * Method:    nativePredictAgeWithCrop
 * Signature: (Lcom/seetaface/v6/SeetaImageData;[Lcom/seetaface/v6/SeetaPointF;)I
 */
JNIEXPORT jint JNICALL Java_com_seetaface_v6_AgePredictor_nativePredictAgeWithCrop
  (JNIEnv *, jobject, jobject, jobjectArray);

/*
 * Class:     com_seetaface_v6_AgePredictor
 * Method:    nativeSetProperty
 * Signature: (ID)V
 */
JNIEXPORT void JNICALL Java_com_seetaface_v6_AgePredictor_nativeSetProperty
  (JNIEnv *, jobject, jint, jdouble);

/*
 * Class:     com_seetaface_v6_AgePredictor
 * Method:    nativeGetProperty
 * Signature: (I)D
 */
JNIEXPORT jdouble JNICALL Java_com_seetaface_v6_AgePredictor_nativeGetProperty
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
