/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_seetaface_v6_FaceImagePreprocessor */

#ifndef _Included_com_seetaface_v6_FaceImagePreprocessor
#define _Included_com_seetaface_v6_FaceImagePreprocessor
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_seetaface_v6_FaceImagePreprocessor
 * Method:    processBitmap
 * Signature: (Landroid/graphics/Bitmap;)Lcom/seetaface/v6/SeetaImageData;
 */
JNIEXPORT jobject JNICALL Java_com_seetaface_v6_FaceImagePreprocessor_processBitmap
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_seetaface_v6_FaceImagePreprocessor
 * Method:    processYUVData
 * Signature: ([BIII)Lcom/seetaface/v6/SeetaImageData;
 */
JNIEXPORT jobject JNICALL Java_com_seetaface_v6_FaceImagePreprocessor_processYUVData
  (JNIEnv *, jobject, jbyteArray, jint, jint, jint);

/*
 * Class:     com_seetaface_v6_FaceImagePreprocessor
 * Method:    processSplitYUVData
 * Signature: ([B[B[BII)Lcom/seetaface/v6/SeetaImageData;
 */
JNIEXPORT jobject JNICALL Java_com_seetaface_v6_FaceImagePreprocessor_processSplitYUVData
  (JNIEnv *, jobject, jbyteArray, jbyteArray, jbyteArray, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
