/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_seetaface_v6_FaceRecognizer */

#ifndef _Included_com_seetaface_v6_FaceRecognizer
#define _Included_com_seetaface_v6_FaceRecognizer
#ifdef __cplusplus
extern "C" {
#endif
#undef com_seetaface_v6_FaceRecognizer_PROPERTY_NUMBER_THREADS
#define com_seetaface_v6_FaceRecognizer_PROPERTY_NUMBER_THREADS 4L
#undef com_seetaface_v6_FaceRecognizer_PROPERTY_ARM_CPU_MODE
#define com_seetaface_v6_FaceRecognizer_PROPERTY_ARM_CPU_MODE 5L
/*
 * Class:     com_seetaface_v6_FaceRecognizer
 * Method:    nativeCreateEngine
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_seetaface_v6_FaceRecognizer_nativeCreateEngine
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_seetaface_v6_FaceRecognizer
 * Method:    nativeDestroyEngine
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_seetaface_v6_FaceRecognizer_nativeDestroyEngine
  (JNIEnv *, jobject);

/*
 * Class:     com_seetaface_v6_FaceRecognizer
 * Method:    nativeGetCropFaceWidth
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_seetaface_v6_FaceRecognizer_nativeGetCropFaceWidth
  (JNIEnv *, jobject);

/*
 * Class:     com_seetaface_v6_FaceRecognizer
 * Method:    nativeGetCropFaceHeight
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_seetaface_v6_FaceRecognizer_nativeGetCropFaceHeight
  (JNIEnv *, jobject);

/*
 * Class:     com_seetaface_v6_FaceRecognizer
 * Method:    nativeGetCropFaceChannels
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_seetaface_v6_FaceRecognizer_nativeGetCropFaceChannels
  (JNIEnv *, jobject);

/*
 * Class:     com_seetaface_v6_FaceRecognizer
 * Method:    nativeCropFace
 * Signature: (Lcom/seetaface/v6/SeetaImageData;[Lcom/seetaface/v6/SeetaPointF;Lcom/seetaface/v6/SeetaImageData;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_seetaface_v6_FaceRecognizer_nativeCropFace__Lcom_seetaface_v6_SeetaImageData_2_3Lcom_seetaface_v6_SeetaPointF_2Lcom_seetaface_v6_SeetaImageData_2
  (JNIEnv *, jobject, jobject, jobjectArray, jobject);

/*
 * Class:     com_seetaface_v6_FaceRecognizer
 * Method:    nativeCropFace
 * Signature: (Lcom/seetaface/v6/SeetaImageData;[Lcom/seetaface/v6/SeetaPointF;)Lcom/seetaface/v6/SeetaImageData;
 */
JNIEXPORT jobject JNICALL Java_com_seetaface_v6_FaceRecognizer_nativeCropFace__Lcom_seetaface_v6_SeetaImageData_2_3Lcom_seetaface_v6_SeetaPointF_2
  (JNIEnv *, jobject, jobject, jobjectArray);

/*
 * Class:     com_seetaface_v6_FaceRecognizer
 * Method:    nativeGetCropFaceWidthV2
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_seetaface_v6_FaceRecognizer_nativeGetCropFaceWidthV2
  (JNIEnv *, jobject);

/*
 * Class:     com_seetaface_v6_FaceRecognizer
 * Method:    nativeGetCropFaceHeightV2
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_seetaface_v6_FaceRecognizer_nativeGetCropFaceHeightV2
  (JNIEnv *, jobject);

/*
 * Class:     com_seetaface_v6_FaceRecognizer
 * Method:    nativeGetCropFaceChannelsV2
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_seetaface_v6_FaceRecognizer_nativeGetCropFaceChannelsV2
  (JNIEnv *, jobject);

/*
 * Class:     com_seetaface_v6_FaceRecognizer
 * Method:    nativeCropFaceV2
 * Signature: (Lcom/seetaface/v6/SeetaImageData;[Lcom/seetaface/v6/SeetaPointF;Lcom/seetaface/v6/SeetaImageData;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_seetaface_v6_FaceRecognizer_nativeCropFaceV2__Lcom_seetaface_v6_SeetaImageData_2_3Lcom_seetaface_v6_SeetaPointF_2Lcom_seetaface_v6_SeetaImageData_2
  (JNIEnv *, jobject, jobject, jobjectArray, jobject);

/*
 * Class:     com_seetaface_v6_FaceRecognizer
 * Method:    nativeCropFaceV2
 * Signature: (Lcom/seetaface/v6/SeetaImageData;[Lcom/seetaface/v6/SeetaPointF;)Lcom/seetaface/v6/SeetaImageData;
 */
JNIEXPORT jobject JNICALL Java_com_seetaface_v6_FaceRecognizer_nativeCropFaceV2__Lcom_seetaface_v6_SeetaImageData_2_3Lcom_seetaface_v6_SeetaPointF_2
  (JNIEnv *, jobject, jobject, jobjectArray);

/*
 * Class:     com_seetaface_v6_FaceRecognizer
 * Method:    nativeGetExtractFeatureSize
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_seetaface_v6_FaceRecognizer_nativeGetExtractFeatureSize
  (JNIEnv *, jobject);

/*
 * Class:     com_seetaface_v6_FaceRecognizer
 * Method:    nativeExtractFace
 * Signature: (Lcom/seetaface/v6/SeetaImageData;[Lcom/seetaface/v6/SeetaPointF;[F)Z
 */
JNIEXPORT jboolean JNICALL Java_com_seetaface_v6_FaceRecognizer_nativeExtractFace
  (JNIEnv *, jobject, jobject, jobjectArray, jfloatArray);

/*
 * Class:     com_seetaface_v6_FaceRecognizer
 * Method:    nativeExtractCropFace
 * Signature: (Lcom/seetaface/v6/SeetaImageData;[F)Z
 */
JNIEXPORT jboolean JNICALL Java_com_seetaface_v6_FaceRecognizer_nativeExtractCropFace
  (JNIEnv *, jobject, jobject, jfloatArray);

/*
 * Class:     com_seetaface_v6_FaceRecognizer
 * Method:    nativeCompareFace
 * Signature: ([F[F)F
 */
JNIEXPORT jfloat JNICALL Java_com_seetaface_v6_FaceRecognizer_nativeCompareFace
  (JNIEnv *, jobject, jfloatArray, jfloatArray);

/*
 * Class:     com_seetaface_v6_FaceRecognizer
 * Method:    nativeSetProperty
 * Signature: (ID)V
 */
JNIEXPORT void JNICALL Java_com_seetaface_v6_FaceRecognizer_nativeSetProperty
  (JNIEnv *, jobject, jint, jdouble);

/*
 * Class:     com_seetaface_v6_FaceRecognizer
 * Method:    nativeGetProperty
 * Signature: (I)D
 */
JNIEXPORT jdouble JNICALL Java_com_seetaface_v6_FaceRecognizer_nativeGetProperty
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
