/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_seetaface_v6_EyeStateDetector */

#ifndef _Included_com_seetaface_v6_EyeStateDetector
#define _Included_com_seetaface_v6_EyeStateDetector
#ifdef __cplusplus
extern "C" {
#endif
#undef com_seetaface_v6_EyeStateDetector_EYE_STATE_CLOSE
#define com_seetaface_v6_EyeStateDetector_EYE_STATE_CLOSE 0L
#undef com_seetaface_v6_EyeStateDetector_EYE_STATE_OPEN
#define com_seetaface_v6_EyeStateDetector_EYE_STATE_OPEN 1L
#undef com_seetaface_v6_EyeStateDetector_EYE_STATE_RANDOM
#define com_seetaface_v6_EyeStateDetector_EYE_STATE_RANDOM 2L
#undef com_seetaface_v6_EyeStateDetector_EYE_STATE_UNKNOWN
#define com_seetaface_v6_EyeStateDetector_EYE_STATE_UNKNOWN 3L
#undef com_seetaface_v6_EyeStateDetector_PROPERTY_NUMBER_THREADS
#define com_seetaface_v6_EyeStateDetector_PROPERTY_NUMBER_THREADS 4L
#undef com_seetaface_v6_EyeStateDetector_PROPERTY_ARM_CPU_MODE
#define com_seetaface_v6_EyeStateDetector_PROPERTY_ARM_CPU_MODE 5L
/*
 * Class:     com_seetaface_v6_EyeStateDetector
 * Method:    nativeCreateEngine
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_seetaface_v6_EyeStateDetector_nativeCreateEngine
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_seetaface_v6_EyeStateDetector
 * Method:    nativeDestroyEngine
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_seetaface_v6_EyeStateDetector_nativeDestroyEngine
  (JNIEnv *, jobject);

/*
 * Class:     com_seetaface_v6_EyeStateDetector
 * Method:    nativeEyeStateDetect
 * Signature: (Lcom/seetaface/v6/SeetaImageData;[Lcom/seetaface/v6/SeetaPointF;Ljava/lang/Integer;Ljava/lang/Integer;)V
 */
JNIEXPORT void JNICALL Java_com_seetaface_v6_EyeStateDetector_nativeEyeStateDetect
  (JNIEnv *, jobject, jobject, jobjectArray, jobject, jobject);

/*
 * Class:     com_seetaface_v6_EyeStateDetector
 * Method:    nativeSetProperty
 * Signature: (ID)V
 */
JNIEXPORT void JNICALL Java_com_seetaface_v6_EyeStateDetector_nativeSetProperty
  (JNIEnv *, jobject, jint, jdouble);

/*
 * Class:     com_seetaface_v6_EyeStateDetector
 * Method:    nativeGetProperty
 * Signature: (I)D
 */
JNIEXPORT jdouble JNICALL Java_com_seetaface_v6_EyeStateDetector_nativeGetProperty
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
