/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_seetaface_v6_MaskDetector */

#ifndef _Included_com_seetaface_v6_MaskDetector
#define _Included_com_seetaface_v6_MaskDetector
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_seetaface_v6_MaskDetector
 * Method:    nativeCreateEngine
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_seetaface_v6_MaskDetector_nativeCreateEngine
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_seetaface_v6_MaskDetector
 * Method:    nativeDestroyEngine
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_seetaface_v6_MaskDetector_nativeDestroyEngine
  (JNIEnv *, jobject);

/*
 * Class:     com_seetaface_v6_MaskDetector
 * Method:    nativeDetectMask
 * Signature: (Lcom/seetaface/v6/SeetaImageData;Lcom/seetaface/v6/SeetaRect;[F)Z
 */
JNIEXPORT jboolean JNICALL Java_com_seetaface_v6_MaskDetector_nativeDetectMask
  (JNIEnv *, jobject, jobject, jobject, jfloatArray);

#ifdef __cplusplus
}
#endif
#endif
